// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// to_hexstr
std::string to_hexstr(int x, int pad);
RcppExport SEXP _striprtf_to_hexstr(SEXP xSEXP, SEXP padSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type pad(padSEXP);
    rcpp_result_gen = Rcpp::wrap(to_hexstr(x, pad));
    return rcpp_result_gen;
END_RCPP
}
// hex_to_int
IntegerVector hex_to_int(std::string h, char sep);
RcppExport SEXP _striprtf_hex_to_int(SEXP hSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type h(hSEXP);
    Rcpp::traits::input_parameter< char >::type sep(sepSEXP);
    rcpp_result_gen = Rcpp::wrap(hex_to_int(h, sep));
    return rcpp_result_gen;
END_RCPP
}
// strip_helper
List strip_helper(CharacterMatrix match_mat, CharacterVector dest_names, CharacterVector special_keys, CharacterVector special_hex, IntegerVector code_before, IntegerVector code_after, bool verbose);
RcppExport SEXP _striprtf_strip_helper(SEXP match_matSEXP, SEXP dest_namesSEXP, SEXP special_keysSEXP, SEXP special_hexSEXP, SEXP code_beforeSEXP, SEXP code_afterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type match_mat(match_matSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dest_names(dest_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type special_keys(special_keysSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type special_hex(special_hexSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type code_before(code_beforeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type code_after(code_afterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(strip_helper(match_mat, dest_names, special_keys, special_hex, code_before, code_after, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_striprtf_to_hexstr", (DL_FUNC) &_striprtf_to_hexstr, 2},
    {"_striprtf_hex_to_int", (DL_FUNC) &_striprtf_hex_to_int, 2},
    {"_striprtf_strip_helper", (DL_FUNC) &_striprtf_strip_helper, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_striprtf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
