// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// to_hexstr
std::string to_hexstr(int x, int pad);
RcppExport SEXP striprtf_to_hexstr(SEXP xSEXP, SEXP padSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type pad(padSEXP);
    rcpp_result_gen = Rcpp::wrap(to_hexstr(x, pad));
    return rcpp_result_gen;
END_RCPP
}
// strip_helper
List strip_helper(CharacterMatrix match_mat);
RcppExport SEXP striprtf_strip_helper(SEXP match_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type match_mat(match_matSEXP);
    rcpp_result_gen = Rcpp::wrap(strip_helper(match_mat));
    return rcpp_result_gen;
END_RCPP
}
