# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

strip_helper <- function(match_list) {
    .Call('striprtf_strip_helper', PACKAGE = 'striprtf', match_list)
}

